//
//  RefineShowingData.swift
//  YaCupaiobvo
//
//  Created by  on 2026/1/23.
//

import UIKit

class RefineShowingData {
    static let YACUAIOBVO_HUB = RefineShowingData()
    
    var YACUAIOBVO_home_datas: [[String: Any]] = [
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h1_1", "YACUAIOBVO_h1_2", "YACUAIOBVO_h1_3"],
         "YACUAIOBVOtitle": "Summer Urban Aesthetic",
         "YACUAIOBVOconten": "Exploring the minimalist lines of downtown architecture in linen textures.",
         "YACUAIOBVOlikeCount": 142,
         "YACUAIOBVOIfNeedUnlock": true,
         "YACUAIOBVOIAttitudeIcon": "heart.fill"],
        
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h2_1", "YACUAIOBVO_h2_2", "YACUAIOBVO_h2_3"],
         "YACUAIOBVOtitle": "Midnight Neon Session",
         "YACUAIOBVOconten": "High-contrast styling for late-night city walks and social gatherings.",
         "YACUAIOBVOlikeCount": 89,
         "YACUAIOBVOIfNeedUnlock": false,
         "YACUAIOBVOIAttitudeIcon": "star.fill"],
        
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h3_1", "YACUAIOBVO_h3_2", "YACUAIOBVO_h3_3"],
         "YACUAIOBVOtitle": "Vintage Denim Revival",
         "YACUAIOBVOconten": "How to layer 90s heritage pieces with modern luxury accessories.",
         "YACUAIOBVOlikeCount": 256,
         "YACUAIOBVOIfNeedUnlock": true,
         "YACUAIOBVOIAttitudeIcon": "bolt.circle.fill"],
        
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h4_1","YACUAIOBVO_h4_2","YACUAIOBVO_h4_3"],
         "YACUAIOBVOtitle": "Silk & Shadow",
         "YACUAIOBVOconten": "The interplay of natural morning light on premium silk fabrics.",
         "YACUAIOBVOlikeCount": 67,
         "YACUAIOBVOIfNeedUnlock": false,
         "YACUAIOBVOIAttitudeIcon": "leaf.fill"],
        
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h5_1", "YACUAIOBVO_h5_2"],
         "YACUAIOBVOtitle": "Brutalism in Fashion",
         "YACUAIOBVOconten": "Structured coats and heavy boots for the winter concrete jungle.",
         "YACUAIOBVOlikeCount": 310,
         "YACUAIOBVOIfNeedUnlock": true,
         "YACUAIOBVOIAttitudeIcon": "shield.fill"],
        
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h6_1","YACUAIOBVO_h6_2","YACUAIOBVO_h6_3"],
         "YACUAIOBVOtitle": "Ethereal Pastels",
         "YACUAIOBVOconten": "Soft palettes for a gentle transition into the spring season.",
         "YACUAIOBVOlikeCount": 45,
         "YACUAIOBVOIfNeedUnlock": false,
         "YACUAIOBVOIAttitudeIcon": "cloud.sun.fill"],
        
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h7_1", "YACUAIOBVO_h7_2", "YACUAIOBVO_h7_3"],
         "YACUAIOBVOtitle": "Cyber-Punk Accessories",
         "YACUAIOBVOconten": "Integrating tech-wear elements into daily casual outfits.",
         "YACUAIOBVOlikeCount": 128,
         "YACUAIOBVOIfNeedUnlock": true,
         "YACUAIOBVOIAttitudeIcon": "antenna.radiowaves.left.and.right"],
        
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h8_1", "YACUAIOBVO_h8_2","YACUAIOBVO_h8_3"],
         "YACUAIOBVOtitle": "Golden Hour Portraits",
         "YACUAIOBVOconten": "Capturing the warmth of sunset through amber lenses and warm tones.",
         "YACUAIOBVOlikeCount": 99,
         "YACUAIOBVOIfNeedUnlock": false,
         "YACUAIOBVOIAttitudeIcon": "camera.shutter.button.fill"],
        
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h9_1","YACUAIOBVO_h9_2"],
         "YACUAIOBVOtitle": "Monochrome Discipline",
         "YACUAIOBVOconten": "The art of wearing a single color without losing depth or texture.",
         "YACUAIOBVOlikeCount": 213,
         "YACUAIOBVOIfNeedUnlock": true,
         "YACUAIOBVOIAttitudeIcon": "moon.phase.new.moon"],
        
        ["YACUAIOBVOimglist": ["YACUAIOBVO_h10_1", "YACUAIOBVO_h10_2"],
         "YACUAIOBVOtitle": "Rural Escape Styling",
         "YACUAIOBVOconten": "Earth tones and durable fabrics for a weekend away from the city.",
         "YACUAIOBVOlikeCount": 54,
         "YACUAIOBVOIfNeedUnlock": false,
         "YACUAIOBVOIAttitudeIcon": "map.fill"]
    ]

    var YACUAIOBVO_user_datas: [[String: Any]] = [
        ["YACUAIOBVO_ID": "user_001",
         "YACUAIOBVO_NICKNAME": "Grace",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_1",
         "YACUAIOBVOlikeCount": 1,
         "YACUAIOBVO_BIO_TEXT": "I see the world through tinted lenses",
         "YACUAIOBVO_WALLET_BALANCE": 1200,
         "YACUAIOBVO_discover_ID": "disco_1",
         "YACUAIOBVO_CommentList": ["Amazing lighting!", "Where is the jacket from?", "Love this vibe"],
         "YACUAIOBVO_discover_title": "Classic Black",
         "YACUAIOBVO_discover_content": "Clean lines that work with any outfit, any time",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_1",
         "YACUAIOBVO_discover_ifLikeed": true,
         "YACUAIOBVO_discover_Likecount": 88],

        ["YACUAIOBVO_ID": "user_002",
         "YACUAIOBVO_NICKNAME": "Alex",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_2",
         "YACUAIOBVOlikeCount": 2,
         "YACUAIOBVO_BIO_TEXT": "Black is not a color, it's an attitude.",
         "YACUAIOBVO_WALLET_BALANCE": 50,
         "YACUAIOBVO_discover_ID": "disco_2",
         "YACUAIOBVO_CommentList": ["So moody!", "Perfect composition"],
         "YACUAIOBVO_discover_title": "Street Mood",
         "YACUAIOBVO_discover_content": "Bold frames that bring instant attitude to casual looks",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_2",
         "YACUAIOBVO_discover_ifLikeed": false,
         "YACUAIOBVO_discover_Likecount": 42],

        ["YACUAIOBVO_ID": "user_003",
         "YACUAIOBVO_NICKNAME": "Elena",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_3",
         "YACUAIOBVOlikeCount": 2,
         "YACUAIOBVO_BIO_TEXT": "Living my best life in silk and cashmere.",
         "YACUAIOBVO_WALLET_BALANCE": 3400,
         "YACUAIOBVO_discover_ID": "disco_3",
         "YACUAIOBVO_CommentList": ["Absolute elegance.", "My daily inspiration"],
         "YACUAIOBVO_discover_title": "Minimal Fit",
         "YACUAIOBVO_discover_content": "Simple sunglasses that keep the focus on the vibe",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_3",
         "YACUAIOBVO_discover_ifLikeed": true,
         "YACUAIOBVO_discover_Likecount": 156],

        ["YACUAIOBVO_ID": "user_004",
         "YACUAIOBVO_NICKNAME": "Leo",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_4",
         "YACUAIOBVOlikeCount": 0,
         "YACUAIOBVO_BIO_TEXT": "Photographer chasing shadows across London.",
         "YACUAIOBVO_WALLET_BALANCE": 10,
         "YACUAIOBVO_discover_ID": "disco_4",
         "YACUAIOBVO_CommentList": ["Great shot!", "The lens flare is perfect"],
         "YACUAIOBVO_discover_title": "Brick Lane Sunset",
         "YACUAIOBVO_discover_content": "Statement sunglasses that turn simple outfits into looks",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_4",
         "YACUAIOBVO_discover_ifLikeed": true,
         "YACUAIOBVO_discover_Likecount": 92],

        ["YACUAIOBVO_ID": "user_005",
         "YACUAIOBVO_NICKNAME": "Maya",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_5",
         "YACUAIOBVOlikeCount": 0,
         "YACUAIOBVO_BIO_TEXT": "Curating the best of Gen-Z street style.",
         "YACUAIOBVO_WALLET_BALANCE": 890,
         "YACUAIOBVO_discover_ID": "disco_5",
         "YACUAIOBVO_CommentList": ["Need this fit now!", "Iconic"],
         "YACUAIOBVO_discover_title": "Retro Touch",
         "YACUAIOBVO_discover_content": "Old-school frames that add character without trying",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_5",
         "YACUAIOBVO_discover_ifLikeed": false,
         "YACUAIOBVO_discover_Likecount": 204],

        ["YACUAIOBVO_ID": "user_006",
         "YACUAIOBVO_NICKNAME": "Julian_Lux",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_6",
         "YACUAIOBVOlikeCount": 3,
         "YACUAIOBVO_BIO_TEXT": "High-end grooming and tailored essentials.",
         "YACUAIOBVO_WALLET_BALANCE": 1500,
         "YACUAIOBVO_discover_ID": "disco_6",
         "YACUAIOBVO_CommentList": ["Sharp look.", "The fit is immaculate"],
         "YACUAIOBVO_discover_title": "Summer Ready",
         "YACUAIOBVO_discover_content": "Light lenses perfect for bright days and easy outfits",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_6",
         "YACUAIOBVO_discover_ifLikeed": true,
         "YACUAIOBVO_discover_Likecount": 33],

        ["YACUAIOBVO_ID": "user_007",
         "YACUAIOBVO_NICKNAME": "Nina_Eco",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_7",
         "YACUAIOBVOlikeCount": 5,
         "YACUAIOBVO_BIO_TEXT": "Sustainable fashion and ethical living.",
         "YACUAIOBVO_WALLET_BALANCE": 220,
         "YACUAIOBVO_discover_ID": "disco_7",
         "YACUAIOBVO_CommentList": ["Thank you for the tips!", "Eco-friendly and stylish"],
         "YACUAIOBVO_discover_title": "City Walk",
         "YACUAIOBVO_discover_content": "Comfortable frames made for long walks and coffee stops",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_7",
         "YACUAIOBVO_discover_ifLikeed": true,
         "YACUAIOBVO_discover_Likecount": 118],

        ["YACUAIOBVO_ID": "user_008",
         "YACUAIOBVO_NICKNAME": "Oscar_Raw",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_8",
         "YACUAIOBVOlikeCount": 6,
         "YACUAIOBVO_BIO_TEXT": "Documentary style fashion photography.",
         "YACUAIOBVO_WALLET_BALANCE": 0,
         "YACUAIOBVO_discover_ID": "disco_8",
         "YACUAIOBVO_CommentList": ["Honest and raw.", "I love the grain"],
         "YACUAIOBVO_discover_title": "Soft Tint",
         "YACUAIOBVO_discover_content": "Subtle colors that make everything feel calmer",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_8",
         "YACUAIOBVO_discover_ifLikeed": false,
         "YACUAIOBVO_discover_Likecount": 27],

        ["YACUAIOBVO_ID": "user_009",
         "YACUAIOBVO_NICKNAME": "Vera_Vogue",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_9",
         "YACUAIOBVOlikeCount": 6,
         "YACUAIOBVO_BIO_TEXT": "Editor. Coffee lover. Always in heels.",
         "YACUAIOBVO_WALLET_BALANCE": 5000,
         "YACUAIOBVO_discover_ID": "disco_9",
         "YACUAIOBVO_CommentList": ["Classy as always.", "Stunning"],
         "YACUAIOBVO_discover_title": "Sharp Lines",
         "YACUAIOBVO_discover_content": "Angular frames that add structure to relaxed outfits",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_9",
         "YACUAIOBVO_discover_ifLikeed": true,
         "YACUAIOBVO_discover_Likecount": 432],

        ["YACUAIOBVO_ID": "user_010",
         "YACUAIOBVO_NICKNAME": "Zane_Retro",
         "YACUAIOBVO_AVATAR_REF": "YACUAIOBVO_av_10",
         "YACUAIOBVOlikeCount": 2,
         "YACUAIOBVO_BIO_TEXT": "90s streetwear archivist.",
         "YACUAIOBVO_WALLET_BALANCE": 660,
         "YACUAIOBVO_discover_ID": "disco_10",
         "YACUAIOBVO_CommentList": ["Grail pieces!", "Amazing collection"],
         "YACUAIOBVO_discover_title": "Everyday Pair",
         "YACUAIOBVO_discover_content": "Reliable sunglasses you reach for without thinking",
         "YACUAIOBVO_discover_pic": "YACUAIOBVO_dp_10",
         "YACUAIOBVO_discover_ifLikeed": true,
         "YACUAIOBVO_discover_Likecount": 76]
    ]
}
